### ISSUE TITLE
MetadataURL not included in the transaction

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-desktop-wallet#298] opened 2022-05-06 13:05 UTC
**Bug Description**
For some reason the metadataURL was not included in the ConfigureBaker transaction, even though an actual functioning URL was entered in the field. Instead of showing the URL the transaction slip showed Empty and not URL was shown on the Ledger, so it seems like the URL entered was just ignored. 

The error doesn't always seem to happen though, so it's not immediately reproducible.

![image](https://user-images.githubusercontent.com/76045015/167136640-e71c6942-e805-426b-9380-2faaffe9a2a3.png)
![image](https://user-images.githubusercontent.com/76045015/167136685-64d12fcf-44b3-4f72-902c-33f26114f6e7.png)

**Versions**
- Software Version: 1.4.0-beta.2
- OS: MacOS
- Browser
- Mobile device, if applicable

**Comment by shjortConcordium** [comment] 2022-05-09 07:22
Yeah, I'm unable to reproduce this :thinking:

**Comment by orhoj** [comment] 2022-05-09 08:27
I cannot reproduce this either. @jens-concordium, can you produce some more exact steps for how to reproduce this? Otherwise we can probably not move forward with this one.

**Comment by jens-concordium** [comment] 2022-05-09 08:34
Same here, can't reproduce it again. Maybe we can just close it again, and then take it up later if someone experience it again?

**Comment by abizjak** [comment] 2022-05-30 13:50
Since nobody can reproduce I'm closing it.

**Closed by abizjak** 2022-05-30 13:50 UTC
Labels: [Prio] Low, [Type] Bug
